Implement more RESTful routes
python-discord/pixels pull request #119
Opened 2021-06-29 13:30 UTC by Bluenix2

I am starting this pull request as a draft so that there's no conflicts between work. Resolves #115.

So I've thought about these a bit more, and it would probably be better to do the following..
- GET /canvas/                              *Get the size; this should be the first one the user tries, that's why it's the simplest*
- GET /canvas/pixels                     *Get all pixels*
- GET /canvas/pixels?x=0&y=0    *Get a specific pixel*
- PUT                                             *Set a specific pixel, unsure which one is best*
  - /canvas/pixels    *x, y and rgb is in the body*
  - /canvas/pixels?x=0&y=0    *only rgb in the body, but conforms better to how you get a pixel*

The biggest issue with this *second proposal* is that now we have a "conflict" of `GET /canvas/pixels` and `GET/canvas/pixels?x=0&y=0`. We cannot have 2 documentation entries to outline this (if we use one that automatically generates documentation from the openapi spec).
> Query string parameters must not be included in paths. They should be defined as query parameters instead.
> This also means that it is impossible to have multiple paths that differ only in query string, such as:
> ```
> GET /users?firstName=value&lastName=value
> GET /users?role=value
> ```
> This is because Swagger considers a unique operation as a combination of a path and the HTTP method, and additional parameters do not make the operation unique.

Of course it's not impossible, we can have one shared function. But this means we need to merge `get_pixel` and `pixels` doc-string. Leading to more confusion than UX we get.

That makes the first proposal conflict free, that said there may be improvements to be made?
- **GET /canvas/size**
- **GET /canvas/**
- GET /canvas/pixels?x=0&y=0
- PUT
  - /canvas/pixels
  - /canvas/pixels?x=0&y=0

2021-06-29 13:43 UTC, jb3 commented
Feedback on endpoints:
- Size should explicitly be in the endpoint, so something like `GET /canvas/size`.
- Fetching an individual pixel should not use pixels plural imo, I'd rather keep it as `GET /canvas/pixel?x=1&y=1` or put it in the URL parameters like `GET /canvas/pixels/1/2` and document the order.
- I don't like PUT with URL parameter *and* a body, it doesn't make sense. The document being created should be complete in the body, not partials in two different places.

2021-06-29 14:24 UTC, Bluenix2 commented
> * Fetching an individual pixel should not use pixels plural imo, I'd rather keep it as `GET /canvas/pixel?x=1&y=1` or put it in the URL parameters like `GET /canvas/pixels/1/2` and document the order.

Ah, interesting. The way I see it is that we're making a GET requests to get the pixels, but we're picking a specific one (using query parameters to narrow down). But yes using `GET /canvas/pixel?x=0&y=0` and `GET /canvas/pixelS` (plurals) would remove that conflict I was talking about.

> I don't like PUT with URL parameter and a body, it doesn't make sense. The document being created should be complete in the body, not partials in two different places.

Yeah the former would be better and then use the singular form as we do getting a specific pixel.

2021-07-01 12:02 UTC, Bluenix2 commented
While this is being done, should moderation endpoints also get similar changes?

2021-07-20 23:19 UTC, Bluenix2 commented
I have now done some basic testing and squashed the commits so that this can be rebased.

2021-08-06 22:32 UTC, ChrisLovering requested changes

2021-08-06 22:32 UTC, ChrisLovering commented on pixels/endpoints/general.py
> +secure = APIRouter(dependencies=[Depends(auth.JWTBearer())])  # We include this at the bottom
```suggestion
# We include this at the bottom
secure = APIRouter(dependencies=[Depends(auth.JWTBearer())], tags=["Canvas Endpoints"])
```

2021-08-06 23:11 UTC, ChrisLovering approved these changes

2021-08-06 23:19 UTC, merged